### PR TITLE
Correct failed geoIP attempts showing as USA

### PR DESCRIPTION
**Pull request by overint**
Currently if the geoIP library does not pick up a country when logging advanced stats, if defaults to USA.
This is incorrect, so I have modified the defaults and changed the query for the map to ignore visits with an empty country.

### CODE REVIEW

**Comment by overint** [comment]
@cydrobolt

**Comment by overint** [comment]
@cydrobolt

**Comment by overint** [comment]
@cydrobolt 
Any thoughts?

**Comment by overint** [comment]
@cydrobolt
Any thoughts?

**Comment by cydrobolt** [comment]
Merged in f9622d7

**Pull request closed without merging**
