### PR TITLE
fix secret urls

### PR DESCRIPTION
**Pull request by berrythesoftwarecodeprogrammar**
secret urls werent working for me until i changed this. it wouldnt accept the keys because of the previous code

### CODE REVIEW

**Comment by cydrobolt** [comment]
I'm not sure why secret URLs were not working for you, but I don't think this is the correct way to fix it.  Can you explain your reasoning? 

On line 38, you changed the code to only check if a key is sent. This means that it will return true as long as you send a key,  no matter what the contents of the key are.  This seems to defeat the point of secret URLs.  Can you show me what's happening on your side?

**Comment by berrythesoftwarecodeprogrammar** [comment]
sorry i shouldve just opened an issue before attempting to merge.

but anyway, my code is actually checking the keys against each other. it seems like your code is the one which only checks if a key is sent. i used the git version of polr from the night i commented. do secret urls work properly for you? after my code change it seems to work properly (only with the correct key). before it would always return an error as if the wrong key was supplied

**Comment by cydrobolt** [comment]
Yes,  they work properly for me :)

It took me a while to understand how it worked. In `r.php`, this line `$sent_lkey = isset($_GET[$lkey]);` is used to check against the proper key. Since we already know which key we are expecting thorough `$lkey`, we are checking for its existence. This is the reason we are only check if it is set,  not whether they are equal. 

If this change fixes the issue for you,  I'd encourage you to continue using it.  Every environment can be different and some things don't seem to work everywhere :(

**Comment by berrythesoftwarecodeprogrammar** [comment]
hmm thats really weird. it just didnt work for me at all with the normal code. could it be php version or something? idk. ill see if it still happens after you release 2.0 and investigate properly

**Comment by cydrobolt** [comment]
2.0 will handle this in a completely different way. Hopefully that should fix the issue.

**Pull request closed without merging**
