### PR TITLE
Disable anything but PHP Error with Debug Mode off

### PR DESCRIPTION
**Pull request by mihawk90**
Disable all PHP Warning/Notice/Whatever Outputs except Errors when `$debug` mode is off.

People who don't want polrs internal outputs probably don't want php debug output either.

Admittedly, this probably isn't an issue on 99% of hosts (disabled php debug by default), but for consistency's sake, it doesn't hurt.

### CODE REVIEW

**Comment by Cydrobolt** [comment]
Would this output error messages in a case where it is disabled on the host? We generally don't want any messages to show up unless we output it in production. We might also want to use false instead of FALSE in the if statement,  in addition to replacing the 1/0 in the line comment with true/false for consistency :)

**Comment by mihawk90** [comment]
What do you mean, what would output anything if what is disabled? I can't follow you there, I'm apparently a little slow on that :D 

As long as there is no PHP error it won't show anything, but if there is an error the administrators/visitors should know something went wrong and not just get a blank page, right?

Unless of course `$debug` is turned on in which case error reporting isn't touched and is the webservers default (which is only error for most shared hosts and for local dev servers it's mostly warning and/or notice, or even strict).
In my case (I have XDebug installed) there is even an xdebug box that overlays the actual page elements.

But do you mean if it will display Errors if errors are turned off in the php.ini? Yes, unless `display_errors` is turned off in php.ini as well (I believe, I actually need to test this). The thing is though errors shouldn't happen when we write the code properly, the execution will stop anyway so we might as well tell the User why it is stopping and not just display a blank page.

But maybe I misunderstood you completely ;)

**Comment by Cydrobolt** [comment]
I think you understood me correctly.  Even though in a perfect world no errors should exist,  in practice errors do happen and when they do,  we shouldn't show the actual error from the server. There can be private information,  and many other problems associated with leaking error information or a stack trace.

**Comment by mihawk90** [comment]
Hm I definitely see what you mean, not quite sure how we can go about to disable errors completely. I never tried it but I think ` error_reporting( 0 )` should work... need to try it out later.

**Comment by Cydrobolt** [comment]
Yeah, that would work better imho

**Comment by mihawk90** [comment]
So I just checked the possibility with a simple snippet:

```PHP
$debug = false; // Set to 1 in order to enable debug mode (shows sensitive database info), use for troubleshooting
if ( $debug === FALSE ) {
    error_reporting( E_ERROR );
}
require("blabla.blub");
```

And funny enough it didn't show an error in the front-end... TIL~
Apparently this type of error is reported as an `E_COMPILE_ERROR`:
> Fatal compile-time errors. This is like an E_ERROR, except it is generated by the Zend Scripting Engine.

Pretty sure I made triggered a lot of regular `E_ERROR`s in my life but I can't find one for a simple test like this right now :D

**Comment by Cydrobolt** [comment]
No. `$debug` is not in config.php and is not written in setup because it should almost always be off. Only developers who can find it should be turning it on, not the average config file tinkerer. Also, the reason you didn't receive an error on the page from your parse error is because PHP doesn't show parse errors on the frontend. Those don't show anywhere unless you use the `php` command to lint the file. 

Personally, I think turning off all errors is probably best.

**Comment by Cydrobolt** [comment]
This looks pretty good! Have you tested this to be working?

**Comment by mihawk90** [comment]
Oops, forgot to answer here. Yes, everything tested as always ;)

**Pull request merged**
