### PR TITLE
Fixed link in stats page not being text-wrapped

### PR DESCRIPTION
**Pull request by gurgeng**
The links on the stats page of the generated would overflow on the x axis because of url length

### CODE REVIEW

**Comment by cydrobolt** [comment]
Did you test this change? Can you share a screenshot?

**Comment by gurgeng** [comment]
Yes I have tested it

**Before:**
before

**After:**
after

**Inspector:**
inspector

**Comment by cydrobolt** [comment]
I've made some changes to the stats page since you opened this PR. Could you update your pull request to work with the new changes?

Thank you!

**Comment by cydrobolt** [comment]
Fixed in 21e465e149282004840d0e9fe9c1ad1b0b41974b

**Pull request closed without merging**
