### PR TITLE
QR Code of shortened URL

### LINKED ISSUE #347: Create QR Code of shortened URL
I think I'd be nice to show the qr code of the shortened URL below the URL in clear text.
The qr code might be generated temporarily as SVG or PNG in php/javascript source.

## Expected Behavior

After submitting the Long-URL the URL is shortened. Below the line with the Short-URL the QR code ought to appear.

## Current Behavior

The URL is only shortened.

## Context

I use polr to share links to my site. If I want to share the link via qr code I have to manually generate it.

### PR DESCRIPTION
**Pull request by Eragos**
Create QR code with endroid/QrCode library

Fixes #347

### CODE REVIEW

**Comment by cydrobolt** [comment]
If we're interested in creating a QR code for generated URLs, we should generate the QR code on the client side. There is no reason to generate it server side.

**Comment by cookiekiller** [comment]
https://davidshimjs.github.io/qrcodejs/

**Comment by overint** [comment]
@cydrobolt, would you like me to submit a pull request to do this client side?

**Comment by cydrobolt** [comment]
@overint yeah, that would be helpful. If it's a feature you think would add value to Polr, go ahead :)

**Comment by cydrobolt** [comment]
Closed in favor of #375

**Pull request closed without merging**
