### PR TITLE
Update createurl.php

### PR DESCRIPTION
**Pull request by castanley**
Added the installed site URL to the list of URLs that are already shortened to prevent any redirect loops.

### CODE REVIEW

**Comment by castanley** [comment]
Pulled from master to add installed url to list of already shortened urls

**Comment by Cydrobolt** [comment]
This is helpful! Have you tested this to be working? 

Also: don't include an explanation of your changes in the form of comments on the actual code. We don't want to pollute it with comments for changes we make. That is better suited for a PR.

**Comment by Cydrobolt** [comment]
If this is tested to be working,  please remove the comment you added on top of the array and I'll merge it. 

Thanks!

**Comment by castanley** [comment]
I can confirm that it is working for me on my install. Removed comments!

**Comment by Cydrobolt** [comment]
Thanks!

**Pull request merged**
