### PR TITLE
Fixed regex to include / markers

### PR DESCRIPTION
**Pull request by michaelpawlak**

### CODE REVIEW

**Comment by Cydrobolt** [comment]
Did you fix the issue with `#`s going through the filter?

**Comment by michaelpawlak** [comment]
No. I saw that comment after I made this commit. I will revise the regex as follows:

/'^[\pL\pN\-\._~:\/\?@!\$&'\(\)\*\+,;=%]+$/'

**Comment by Cydrobolt** [comment]
Cool, thanks! The `.htaccess` regex might also need to be revised.

**Comment by michaelpawlak** [comment]
Updated.

'/^[\pL\pN-\._~:\/\?@!\$&\'\(\)\*\+,;=%]+$/'

**Comment by Cydrobolt** [comment]
Seems to work :+1: 
Can you also update the `.htaccess` file? It currently only accepts alphanumeric values.

**Comment by michaelpawlak** [comment]
Which of these need updating?

1. RewriteRule ^([a-zA-Z0-9]+)\?([a-zA-Z0-9]+)$ /r.php?u=$1&lkey=$2 [L,QSA]
2. RewriteRule ^([a-zA-Z0-9]+)/?$ /r.php?u=$1 [L,QSA]
3. RewriteRule ^t-([a-zA-Z0-9]+)/?$ /r.php?u=t-$1 [L,QSA]
RewriteRule ^/?\+([a-zA-Z0-9]+)$ /stats.php?bv=$1 [L,QSA]

**Comment by michaelpawlak** [comment]
Modified .htaccess and createurl.php

**Comment by Cydrobolt** [comment]
That regex doesn't seem to work either, it causes a 500 error on all pages. Maybe you made a typo somewhere? Please try to test these patches using http://c9.io or a local instance.

**Comment by michaelpawlak** [comment]
I will test the patches tomorrow. Once tested I'll push the code.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by Cydrobolt** [comment]
Thanks!

**Comment by Cydrobolt** [comment]
Closing this for inactivity. We might also not want to support those symbols in custom URLs for the sake of special URL types and other complications, but feel free to reopen if you feel like it is needed.

**Pull request closed without merging**
