### PR TITLE
Support Dashes and Underscores in URI #77

### PR DESCRIPTION
**Pull request by mattlt**
Fixes issue #77.

### CODE REVIEW

**Comment by cydrobolt** [comment]
Thanks for making this PR! Maybe you can also update the error message to explain the new changes?

https://github.com/cydrobolt/polr/blob/f426dea6713f594d69dc19c32bd33dce7dff7e39/app/Factories/LinkFactory.php#L60

**Comment by mattlt** [comment]
Hope I'm doing this all correctly. Thanks for making it easy to contribute by offering suggestions and locations.

I'll be able to test more extensively in the next couple days and report back if you want to wait before merging. Anything I should check besides just making sure the links work as they should and fail where they shouldn't?

Thanks,

•• matt

**Comment by cydrobolt** [comment]
I think you can try the new symbols and making sure custom links with those endings all work, also checking that prohibited symbols aren't allowed :)

Here is the route entry -- https://github.com/cydrobolt/polr/blob/master/app/Http/routes.php#L27
I think it should allow dashes and underscores, but we should test to make sure

**Comment by mattlt** [comment]
I've updated my pull request after testing hyphens, underscores, and a few disallowed characters.

Everything seems to be working as you'd expect it.

Thanks,

•• matt

**Comment by cydrobolt** [comment]
Cool, thanks for making the changes :+1:

We might want to exclude the changes to `setup`, however. The base32/base62 options are about the automatically generated endings, not the custom endings. base32/base62 doesn't include special characters.

**Comment by mattlt** [comment]
Reverted the setup changes.

**Comment by cydrobolt** [comment]
Thank you for your contributions!

**Pull request merged**
