### PR TITLE
Manage Users From Admin

### PR DESCRIPTION
**Pull request by ashazar**
Issue #177 and Issue #220 
- Added alert box before deleting a user
- Toggle User 'Active' status (true/false)
- Defined User roles (ADMIN and DEFAULT) in UserHelper, and added ability to change roles. It might be better to handle user roles from a DB table for future needs.
- "Add New User" section
- Saw that i can go to '/signup' page, even POLR_ALLOW_ACCT_CREATION set to false. (It shows error after you fill out the form and submit, though). Changed it to return 404, if it's false.

Note: Couldn't make user role change via Angular. So, it's a standard select tag and a separate JS function.

### CODE REVIEW

**Comment by cydrobolt** [comment]
We're currently revamping the user & link tables. Might require some tweaks to get this working fully after the changes :)

**Comment by ashazar** [comment]
Great! No problem ;)

By the way, found a mini-bug and implemented a work-around. You can reproduce it by following below steps.
In admin panel, click on 'API Info' on a user. 
Toggle API Active status. Close the modal-box. And click API info again.
You'll see that still the previous value written, even it is updated on the DB.

**Comment by cydrobolt** [comment]
Yeah, we're aware of the mini-bug :) see #200
It's caused by expired data (when the key changes, the stored API key and API status that is used to create the modal is "cached" and the data is outdated)

**Comment by cydrobolt** [comment]
@ashazar merged Datatables changes into master. You might have to make some tweaks if you added action buttons to the tables.

**Comment by ashazar** [comment]
Hi @cydrobolt , 
I updated the code.

**Comment by ashazar** [comment]
Solved Issue #200 as well.

**Comment by ashazar** [comment]
Sure, why not.
As mentioned before, it's a work-around ;)

**Comment by cydrobolt** [comment]
I'm making some tweaks to it, but will merge once I'm done making some small stylistic changes. Thank you for your contributions!

**Comment by ashazar** [comment]
Thanks @cydrobolt .
Let me know if something is needed.

**Comment by cydrobolt** [comment]
Merged in 1f4b96758bd503b0e38ecb783b24613297c243c8

**Pull request closed without merging**
